// Generated by CoffeeScript 1.9.3
(function() {
  var AppDispatcher, Assign, Dispatcher;

  Dispatcher = require('flux').Dispatcher;

  Assign = require('object-assign');

  AppDispatcher = Assign(new Dispatcher(), {
    handleViewAction: function(action) {
      this.dispatch({
        source: "VIEW_ACTION",
        action: action
      });
    },
    handleServerAction: function(action) {
      this.dispatch({
        source: "SERVER_ACTION",
        action: action
      });
    }
  });

  module.exports = AppDispatcher;

}).call(this);
