// Generated by CoffeeScript 1.9.3
(function() {
  var Assign, Dispatcher, FluxFactory, Store, _stores;

  Dispatcher = require('../dispatcher/');

  Store = require('../store/');

  Assign = require('object-assign');

  _stores = {};

  FluxFactory = (function() {
    function FluxFactory() {}

    FluxFactory.prototype.getStore = function(name) {
      return _stores[name];
    };

    FluxFactory.prototype.createStore = function(params) {
      _stores[params.name] = Assign({}, Store, params);
      _stores[params.name].dispatcherIndex = Dispatcher.register(function(payload) {
        var _nsp, action, actionType, base;
        action = payload.action;
        actionType = action.actionType.split('.');
        _nsp = actionType.shift(0);
        actionType = actionType.join('.');
        if (_nsp !== _stores[params.name].name) {
          return true;
        }
        if (typeof (base = _stores[params.name])[actionType] === "function") {
          base[actionType](action.data);
        }
        return true;
      });
      _stores[params.name]._init(params.init);
      return _stores[params.name];
    };

    return FluxFactory;

  })();

  module.exports = new FluxFactory();

}).call(this);
